name: auto merge push test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sig/**'

jobs:
  release_gem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: auto_merge_push

      - name: auto merge push
        run: |
          git log -1 --format='%H'
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git merge --ff origin/main
          git push
