name: auto merge push test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sigs/**'

jobs:
  release_gem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: auto_merge_push

        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git merge --ff main
          git push
