name: auto merge push test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sig/**'

jobs:
  release_gem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: auto_merge_push
          fetch-depth: 0
          fetch-tags: true

      - name: auto merge push
        run: |
          git log -1 --format='%H'
          git status
          git merge --ff origin/main
          git push
