name: Check filechange

on:
  push:
    paths:
      - 'lib/monibu/qwerty/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: test
      run: bundle exec rake 'qwerty:checksum:test'
