name: Hook on deleted

on:
  release:
    types: [deleted]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.ref }}
